# Generated by Django 5.0.1 on 2024-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_alter_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AddField(
            model_name='book',
            name='bookauthor',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
